// Product List Data
export const productList = [
  {
    id: 1,
    productName: 'apple',
    price: '$400',
    imageURL: 'assets/images/iphon-1.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 2,
    productName: 'apple',
    price: '$500',
    imageURL: 'assets/images/iphone-2.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 3,
    productName: 'apple',
    price: '$600',
    imageURL: 'assets/images/iphone-3.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  { 
    id: 4,
    productName: 'apple',
    price: '$550',
    imageURL: 'assets/images/iphone-4.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 5,
    productName: 'apple',
    price: '$500',
    imageURL: 'assets/images/iphone-5.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 6,
    productName: 'apple',
    price: '$500',
    imageURL: 'assets/images/iphone-6.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 7,
    productName: 'samsung',
    price: '$300',
    imageURL: 'assets/images/samsung-1.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 8,
    productName: 'samsung',
    price: '$350',
    imageURL: 'assets/images/samsung-2.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 9,
    productName: 'samsung',
    price: '$500',
    imageURL: 'assets/images/samsung-3.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 10,
    productName: 'poco',
    price: '$200',
    imageURL: 'assets/images/poco-1.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 11,
    productName: 'poco',
    price: '$500',
    imageURL: 'assets/images/poco-2.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 12,
    productName: 'poco',
    price: '$100',
    imageURL: 'assets/images/poco-3.jpg',
    category: 'mobile',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 13,
    productName: 'cooker',
    price: '$100',
    imageURL: 'assets/images/elec-1.jpg',
    category: 'electronics',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 14,
    productName: 'kettle',
    price: '$100',
    imageURL: 'assets/images/elec-2.jpg',
    category: 'electronics',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 15,
    productName: 'kettle',
    price: '$100',
    imageURL: 'assets/images/elec-3.jpg',
    category: 'electronics',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 16,
    productName: 'fryer',
    price: '$100',
    imageURL: 'assets/images/elec-4.jpg',
    category: 'electronics',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 17,
    productName: 'cycle',
    price: '$100',
    imageURL: 'assets/images/elec-5.jpg',
    category: 'electronics',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 18,
    productName: 'cycle',
    price: '$100',
    imageURL: 'assets/images/elec-6.jpg',
    category: 'electronics',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 19,
    productName: 'cycle',
    price: '$100',
    imageURL: 'assets/images/elec-7.jpg',
    category: 'electronics',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 20,
    productName: 'book',
    price: '$10',
    imageURL: 'assets/images/elec-8.jpg',
    category: 'electronics',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 21,
    productName: 'book',
    price: '$10',
    imageURL: 'assets/images/book-1.jpg',
    category: 'book',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 22,
    productName: 'book',
    price: '$5',
    imageURL: 'assets/images/book-2.jpg',
    category: 'book',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 23,
    productName: 'book',
    price: '$5',
    imageURL: 'assets/images/book-3.jpg',
    category: 'book',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 24,
    productName: 'book',
    price: '$4',
    imageURL: 'assets/images/book-4.jpg',
    category: 'book',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 25,
    productName: 'book',
    price: '$10',
    imageURL: 'assets/images/book-5.jpg',
    category: 'book',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 26,
    productName: 'book',
    price: '$10',
    imageURL: 'assets/images/book-6.jpg',
    category: 'book',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 27,
    productName: 'book',
    price: '$10',
    imageURL: 'assets/images/book-7.jpg',
    category: 'book',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  },
  {
    id: 28,
    productName: 'book',
    price: '$10',
    imageURL: 'assets/images/book-8.jpg',
    category: 'book',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit felis neque, volutpat vulputate justo condimentum at. Suspendisse consequat ex at magna cursus pharetra. Aliquam aliquam tincidunt consectetur.',
  }
];

// Category Data
export const categoryItem = [
  { id: 1, item: 'Category' },
  { id: 1, item: 'Mobile' },
  { id: 2, item: 'Electronics' },
  { id: 3, item: 'Book' },
];
